% TODO: Add example figures and tables.

% Document setup
\documentclass[11pt]{book}

% Location of the csas-style repository: adjust path as needed
\newcommand{\locRepo}{.}

% Use the style file in the csas-style repository (srFR.sty)
\usepackage{\locRepo/srFR}

% Bibliography style file
\bibliographystyle{../csas-style/res-doc}

%%%% Commands for title page etc %%%%%

% Publication year
\newcommand{\rdYear}{2018}

% Publication month
\newcommand{\rdMonth}{Octobre}

% Approval date (default to publication year and month)
\newcommand{\rdAppDate}{\rdMonth{} 23, \rdYear{}}
% Approver (name\\position)
\newcommand{\rdApp}{Carmel Lowe\\Directrice r\'{e}gionale}

% Report number
\newcommand{\rdNumber}{nnn}

% Region
\newcommand{\rdRegion}{R\'{e}gion du Pacifique}
% Address
\newcommand{\rdAddress}{P\^{e}ches et Oc\'{e}ans Canada\\3190 Hammond Bay Road\\Nanaimo, BC V9T 6N7}

% Phone
\newcommand{\rdPhone}{(250) 756-7208}

% Email
\newcommand{\rdEmail}{csap@dfo-mpo.gc.ca}
% Title
\newcommand{\rdTitle}{\'{E}valuation des stocks de \fishNameFr{} (\emph{\scienceName{}}) en \assessYr{} et pr\'{e}visions pour \forecastYr{}}

% English title
\newcommand{\rdTitleEn}{Status of \fishName{} (\scienceName{}) in \assessYr{} and forecasts for \forecastYr{}}

% Title short
\newcommand{\rdTitleShort}{\fishNameFr{}}

%%%% End of title page commands %%%%%

% Let it begin
\begin{document}

%%%% First page %%%%%

<<setup, warning=FALSE, echo=FALSE, message=FALSE>>=
# Required package(s)
library( knitr )
library( xtable )
library( tidyverse )
library( here )

# Bold and latex symbols
Bold2 <- function(x) {paste('\\textbf{',sanitize(x, type="latex"),'}', sep ='')}

# Paste strings nicely
PasteNicely <- function( x, intChars=", ", nChar="and " ) {
  # Get the length of the vector
  n <- length( x )
  # If there are more than two
  if( n > 2 ) {
    # Make a print-friendly vector
    x[n] <- paste( nChar, x[n], sep="" )
    # Get print friendly values
    res <- paste( x, collapse=intChars )
  } else {  # End if more than two, otherwise
    # Add a space
    nCharSp <- paste( " ", nChar, sep="" )
    # Get print friendly values
    res <- paste( x, collapse=nCharSp )
  }  # End if not more than two
  # Return the results
  return( res )
}  # End PasteNicely function

# Directories
rootd <- here::here()
rootd.data <- file.path(rootd, "data")
rootd.static.figs <- file.path(rootd, "maindoc", "figures")

# Region names by type
allRegionNames <- list(
  major=c("Haida Gwaii (HG)", "Prince Rupert District (PRD)",
    "Central Coast (CC)", "Strait of Georgia (SoG)",
    "West Coast of Vancouver Island (WCVI)"),
  minor=c("Area 27 (A27)", "Area 2 West (A2W)") )
@

% More custom variables
<<variables, child='variables.rnw'>>=
@

% Start the first page
\MakeFirstPage

<<context, child='maindoc/1_contextFR.rnw'>>=
@

<<background, child='maindoc/2_backgroundFR.rnw'>>=
@

<<analysis, child='maindoc/3_analysisFR.rnw'>>=
@

<<conclusions, child='maindoc/4_conclusionsFR.rnw'>>=
@

<<contributors, child='maindoc/5_contributorsFR.rnw'>>=
@

% Generate the approval section
\MakeApproval

<<bibliography, child='maindoc/7_bibliographyFR.rnw'>>=
@

<<tables, child='maindoc/8_tablesFR.rnw'>>=
@

%<<figures, child='maindoc/9_figuresFR.rnw'>>=
%@

% Generate the availability section
\MakeAvailable

<<appendix, child='maindoc/11_appendixFR.rnw'>>=
@

% Fin
\end{document}
