% TODO: Add example figures and tables.

% Document setup
\documentclass[11pt]{book}

% Location of the csas-style repository: adjust path as needed
\newcommand{\locRepo}{.}

% Use the style file in the csas-style repository (sr.sty)
\usepackage{\locRepo/sr}

% Bibliography style file
\bibliographystyle{../csas-style/res-doc}

% Headers and footers
% \lhead{Draft working paper --- Do not cite or circulate}
\lhead{}
\rhead{}

%%%% Commands for title page etc %%%%%

% Publication year
\newcommand{\rdYear}{2018}

% Publication month
\newcommand{\rdMonth}{October}

% Approval date (default to publication year and month)
\newcommand{\apDate}{\rdMonth{} 23, \rdYear{}}

% Report number
\newcommand{\rdNumber}{nnn}

% Region
\newcommand{\rdRegion}{Pacific Region}

% Title
\newcommand{\rdTitle}{Status of \fishName{} (\scienceName{}) in \assessYr{} and forecasts for \forecastYr{}}

% French title
\newcommand{\rdTitleFr}{\'{E}valuation des stocks de hareng du Pacifique (\emph{\scienceName{}}) en \assessYr{} et pr\'{e}vision pour \forecastYr{}}

% Title short
\newcommand{\rdTitleShort}{\fishName{}}

%%%% End of title page commands %%%%%

% Let it begin
\begin{document}

%%%% First page %%%%%

<<setup, warning=FALSE, echo=FALSE, message=FALSE>>=
# Required package(s)
library( knitr )
library( xtable )
library( tidyverse )
library( here )

# Bold and latex symbols
Bold2 <- function(x) {paste('\\textbf{',sanitize(x, type="latex"),'}', sep ='')}

# Paste strings nicely
PasteNicely <- function( x, intChars=", ", nChar="and " ) {
  # Get the length of the vector
  n <- length( x )
  # If there are more than two
  if( n > 2 ) {
    # Make a print-friendly vector
    x[n] <- paste( nChar, x[n], sep="" )
    # Get print friendly values
    res <- paste( x, collapse=intChars )
  } else {  # End if more than two, otherwise
    # Add a space
    nCharSp <- paste( " ", nChar, sep="" )
    # Get print friendly values
    res <- paste( x, collapse=nCharSp )
  }  # End if not more than two
  # Return the results
  return( res )
}  # End PasteNicely function

# Directories
rootd <- here::here()
rootd.data <- file.path(rootd, "data")
rootd.static.figs <- file.path(rootd, "maindoc", "figures")

# Region names by type
allRegionNames <- list(
  major=c("Haida Gwaii (HG)", "Prince Rupert District (PRD)",
    "Central Coast (CC)", "Strait of Georgia (SoG)",
    "West Coast of Vancouver Island (WCVI)"),
  minor=c("Area 27 (A27)", "Area 2 West (A2W)") )
@

% More custom variables
<<variables, child='variables.rnw'>>=
@

% Start the first page
\MakeFirstPage

<<context, child='maindoc/1_context.rnw'>>=
@

<<background, child='maindoc/2_background.rnw'>>=
@

<<analysis, child='maindoc/3_analysis.rnw'>>=
@

<<conclusions, child='maindoc/4_conclusions.rnw'>>=
@

<<contributors, child='maindoc/5_contributors.rnw'>>=
@

<<approved, child='maindoc/6_approved.rnw'>>=
@

<<bibliography, child='maindoc/7_bibliography.rnw'>>=
@

% <<tables, child='maindoc/8_tables.rnw'>>=
% @

<<figures, child='maindoc/9_figures.rnw'>>=
@

<<available, child='maindoc/10_available.rnw'>>=
@

<<appendix, child='maindoc/11_appendix.rnw'>>=
@

% Fin
\end{document}
