\newpage

\section[Available]{This report is available from the}

\begin{center}
Centre for Science Advice\\
\rdRegion{}\\
Fisheries and Oceans Canada\\
3190 Hammond Bay Road\\
Nanaimo, BC V9T 6N7\\
\vspace{0.1cm}
Telephone: (250) 756-7208\\
E-Mail: \href{mailto:csap@dfo-mpo.gc.ca}{csap@dfo-mpo.gc.ca}\\
Internet address: \href{http://www.dfo-mpo.gc.ca/csas-sccs/}{www.dfo-mpo.gc.ca/csas-sccs/}\\
\vspace{0.1cm}
ISSN 1919-3769\\
\copyright{} Her Majesty the Queen in Right of Canada, \rdYear{}\\
\vspace{0.2cm}
\includegraphics[scale=0.96]{\locRepo/images/recycle.png}
\end{center}

Correct citation for this publication:

\hangindent=0.6cm
DFO. \rdYear{}. \rdTitle{}.
DFO Can.\ Sci.\ Advis.\ Sec.\ Sci.\ Resp.
\rdYear{}/\rdNumber{}.

\emph{Aussi disponible en fran\c{c}ais:}

\hangindent=0.6cm
\emph{
MPO. \rdYear{}. \rdTitleFr{}.
Secr.\ can.\ de consult.\ sci.\ du MPO, R\'{e}p.\ des Sci.\
\rdYear{}/\rdNumber{}.
}

\newpage
