% References: adjust paths as needed
\bibliography{../csas-style/example}

Optional for regular Science Responses, and mandatory for Stock Status Updates as these must include the citation for the peer-reviewed Science Advisory Report.

\subsection{Optional paragraph}

[The meeting date and title must be exactly as they appear on the Fisheries and Oceans Science Advisory Schedule.
Be sure to use the default text in the French template for the translation as well as the meeting information on the French version of the schedule.]

This Science Response Report results from the Science Response Process [meeting date and title (e.g., of \rdMonth{} \rdYear{} on the \rdTitle{})].

[Add the following sentence if there are other associated publications that will be posted on the schedule.]

Additional publications from this process will be posted on the DFO Science Advisory Schedule as they become available.

\subsubsection{Guidance on references}

References must be formatted according to the Guide for the Production of Fisheries and Oceans Canada Reports.
References listed in the References Cited section should be publically available when the report is posted on the website.
The only exception is for books or articles that have been accepted for publication (page proof stage or where there is an acceptance letter).
These can be listed followed by the notation ``in press''.
All others should be included in the text as unpublished data.
